# Generated by Django 5.1.6 on 2025-03-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='notification_frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=10),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
