# Generated by Django 5.1.6 on 2025-03-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminprofile_email_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='notification_frequency',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='push_notifications',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='verification_documents',
            field=models.FileField(blank=True, upload_to='business_verification/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='verified_business',
            field=models.BooleanField(default=False),
        ),
    ]
