# Generated by Django 5.1.6 on 2025-03-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_adminprofile_email_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_registration_number',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='verification_documents',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='verified_business',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='notification_frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=10),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
