# Generated by Django 5.1.6 on 2025-03-18 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_businessprofile_business_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonprofitprofile',
            name='verification_documents',
            field=models.FileField(blank=True, help_text='Upload verification documents (PDF or images only).', upload_to='nonprofit_verification', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Only PDF and image files (jpg, jpeg, png) are allowed.')]),
        ),
    ]
