# Generated by Django 5.1.6 on 2025-03-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_nonprofitprofile_verification_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='notification_frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=10),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonprofitprofile',
            name='notification_frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=10),
        ),
        migrations.AddField(
            model_name='nonprofitprofile',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='notification_frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=10),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
