# Generated by Django 5.1.6 on 2025-03-19 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_businessprofile_notification_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_radius', models.DecimalField(blank=True, decimal_places=2, help_text='Preferred radius for food listings (km)', max_digits=5, null=True)),
                ('dietary_preferences', models.TextField(blank=True, help_text='Any dietary preferences')),
                ('push_notifications', models.BooleanField(default=False)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consumer Profile',
                'verbose_name_plural': 'Consumer Profiles',
            },
        ),
    ]
