# Generated by Django 5.1.6 on 2025-03-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_businessprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
    ]
