# Generated by Django 5.1.6 on 2025-03-04 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('expiry_date', models.DateTimeField()),
                ('storage_requirements', models.TextField(blank=True, null=True)),
                ('handling_instructions', models.TextField(blank=True, null=True)),
                ('listing_type', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('DONATION', 'Direct Donation')], default='COMMERCIAL', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_listings/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='food_listings.foodlisting')),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compliant', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks', to=settings.AUTH_USER_MODEL)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_check', to='food_listings.foodlisting')),
            ],
        ),
        migrations.AddIndex(
            model_name='foodlisting',
            index=models.Index(fields=['status', 'expiry_date'], name='food_listin_status_0737d9_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlisting',
            index=models.Index(fields=['supplier', 'status'], name='food_listin_supplie_3689e1_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlisting',
            index=models.Index(fields=['city', 'status'], name='food_listin_city_4aaf58_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlisting',
            index=models.Index(fields=['expiry_date', 'listing_type'], name='food_listin_expiry__439e0b_idx'),
        ),
    ]
