# Generated by Django 5.1.6 on 2025-03-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='minimum_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quantity per request (for bulk requests)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='requires_verification',
            field=models.BooleanField(default=False, help_text='Whether this listing requires nonprofit verification'),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='listing_type',
            field=models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('DONATION', 'Donation'), ('NONPROFIT_ONLY', 'Nonprofit Only')], default='COMMERCIAL', max_length=20),
        ),
    ]
