# Generated by Django 5.1.6 on 2025-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_listings', '0003_foodlisting_food_listin_listing_abcd91_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=10),
        ),
    ]
