# Generated by Django 5.1.6 on 2025-03-05 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('active_users', models.IntegerField(default=0, help_text='Number of active users')),
                ('new_users', models.IntegerField(default=0, help_text='Number of new user registrations')),
                ('business_users_active', models.IntegerField(default=0, help_text='Active business users')),
                ('nonprofit_users_active', models.IntegerField(default=0, help_text='Active nonprofit users')),
                ('volunteer_users_active', models.IntegerField(default=0, help_text='Active volunteer users')),
                ('consumer_users_active', models.IntegerField(default=0, help_text='Active consumer users')),
                ('new_listings_count', models.IntegerField(default=0, help_text='Number of new food listings')),
                ('request_count', models.IntegerField(default=0, help_text='Number of food requests created')),
                ('delivery_count', models.IntegerField(default=0, help_text='Number of deliveries created')),
                ('avg_response_time', models.DurationField(blank=True, help_text='Average time to respond to requests', null=True)),
                ('avg_transaction_value', models.DecimalField(decimal_places=2, default=0, help_text='Average transaction value', max_digits=10)),
                ('request_approval_rate', models.DecimalField(decimal_places=2, default=0, help_text='% of requests approved', max_digits=5)),
                ('transaction_completion_rate', models.DecimalField(decimal_places=2, default=0, help_text='% of transactions completed', max_digits=5)),
                ('delivery_completion_rate', models.DecimalField(decimal_places=2, default=0, help_text='% of deliveries completed', max_digits=5)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, help_text='Average rating of transactions', max_digits=3)),
            ],
            options={
                'verbose_name': 'System Metrics',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_s_date_03e773_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_type', models.CharField(help_text='Type of activity performed', max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='analytics_u_user_id_428695_idx'), models.Index(fields=['activity_type'], name='analytics_u_activit_a5f25d_idx')],
            },
        ),
    ]
