# Generated by Django 5.1.6 on 2025-03-05 18:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_systemmetrics_useractivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('IMPACT', 'Impact Report'), ('TRANSACTION', 'Transaction Report'), ('USER_ACTIVITY', 'User Activity Report'), ('COMPLIANCE', 'Compliance Report'), ('SYSTEM', 'System Performance Report')], max_length=20)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('data', models.JSONField(help_text='Report data in JSON format')),
                ('summary', models.TextField(blank=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_generated'],
                'indexes': [models.Index(fields=['report_type', 'date_generated'], name='analytics_r_report__ae8b37_idx'), models.Index(fields=['date_range_start', 'date_range_end'], name='analytics_r_date_ra_17b660_idx')],
            },
        ),
    ]
