# Generated by Django 5.1.6 on 2025-03-08 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_report'),
        ('food_listings', '0003_foodlisting_food_listin_listing_abcd91_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyanalytics',
            unique_together={('date', 'user', 'listing')},
        ),
        migrations.AlterUniqueTogether(
            name='systemmetrics',
            unique_together={('date',)},
        ),
    ]
