# Generated by Django 5.1.6 on 2025-03-15 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0006_alter_report_generated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="report",
            name="analytics_r_report__ae8b37_idx",
        ),
        migrations.RemoveIndex(
            model_name="report",
            name="analytics_r_date_ra_17b660_idx",
        ),
        migrations.AlterField(
            model_name="report",
            name="generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["-date_generated"], name="analytics_r_date_ge_a80ad9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type"], name="analytics_r_report__06672b_idx"
            ),
        ),
    ]
