# Generated by Django 5.1.6 on 2025-03-17 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_backfill_analytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='impactmetrics',
            name='unique_impact_metrics_date',
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_scheduled'], name='analytics_r_is_sche_a10610_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by'], name='analytics_r_generat_6bbe2f_idx'),
        ),
    ]
