# Generated by Django 5.1.6 on 2025-04-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_report_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('IMPACT', 'Impact Report'), ('TRANSACTION', 'Transaction Report'), ('USER_ACTIVITY', 'User Activity Report'), ('COMPLIANCE', 'Compliance Report'), ('SYSTEM', 'System Performance Report'), ('SUPPLIER', 'Supplier Performance Report')], max_length=20),
        ),
    ]
