# Generated by Django 5.1.6 on 2025-04-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_alter_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmetrics',
            name='avg_response_time',
            field=models.FloatField(blank=True, help_text='Average time to respond to requests (hours)', null=True),
        ),
    ]
