# Generated by Django 5.1.6 on 2025-04-29 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0017_alter_report_report_type'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - Drop the column and recreate it with the float type
            sql="""
                ALTER TABLE analytics_systemmetrics 
                DROP COLUMN IF EXISTS avg_response_time;
                
                ALTER TABLE analytics_systemmetrics 
                ADD COLUMN avg_response_time double precision NULL;
            """,
            # Reverse SQL - If needed to roll back
            reverse_sql="""
                ALTER TABLE analytics_systemmetrics 
                DROP COLUMN IF EXISTS avg_response_time;
                
                ALTER TABLE analytics_systemmetrics 
                ADD COLUMN avg_response_time interval NULL;
            """
        ),
    ]