# Generated by Django 5.1.6 on 2025-03-05 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_completed_at_transaction_completion_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('pickup_window_start', models.DateTimeField()),
                ('pickup_window_end', models.DateTimeField()),
                ('delivery_window_start', models.DateTimeField()),
                ('delivery_window_end', models.DateTimeField()),
                ('pickup_notes', models.TextField(blank=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('estimated_weight', models.DecimalField(decimal_places=2, help_text='Estimated weight in kg', max_digits=5)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated distance in km', max_digits=5, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='transactions.transaction')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'pickup_window_start'], name='transaction_status_b7834f_idx'), models.Index(fields=['volunteer', 'status'], name='transaction_volunte_206b10_idx')],
            },
        ),
    ]
