# Generated by Django 5.1.6 on 2025-03-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_deliveryassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrequest',
            name='beneficiary_count',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated number of beneficiaries', null=True),
        ),
        migrations.AddField(
            model_name='foodrequest',
            name='intended_use',
            field=models.TextField(blank=True, help_text='Description of how the food will be used (required for nonprofit requests)'),
        ),
        migrations.AddField(
            model_name='foodrequest',
            name='is_bulk_request',
            field=models.BooleanField(default=False, help_text='Whether this is a bulk request from a nonprofit'),
        ),
    ]
