# Generated by Django 5.1.6 on 2025-03-05 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_listings', '0003_foodlisting_food_listin_listing_abcd91_idx_and_more'),
        ('transactions', '0004_foodrequest_beneficiary_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foodrequest',
            index=models.Index(fields=['listing', 'status'], name='transaction_listing_85068c_idx'),
        ),
    ]
