# Generated by Django 5.1.6 on 2025-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_foodrequest_transaction_listing_85068c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrequest',
            name='preferred_window_end',
            field=models.TimeField(blank=True, help_text='Preferred end time for delivery/pickup window', null=True),
        ),
        migrations.AddField(
            model_name='foodrequest',
            name='preferred_window_start',
            field=models.TimeField(blank=True, help_text='Preferred start time for delivery/pickup window', null=True),
        ),
    ]
