# Generated by Django 5.1.6 on 2025-03-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_foodrequest_preferred_window_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrequest',
            name='preferred_window_end',
        ),
        migrations.RemoveField(
            model_name='foodrequest',
            name='preferred_window_start',
        ),
        migrations.AddField(
            model_name='foodrequest',
            name='preferred_time',
            field=models.CharField(choices=[('morning', 'Morning: 8 AM - 11 AM'), ('afternoon', 'Afternoon: 12 PM - 4 PM'), ('evening', 'Evening: 5 PM - 8 PM'), ('night', 'Night: 9 PM - 11 PM')], max_length=20, null=True),
        ),
    ]
