# Generated by Django 5.1.6 on 2025-03-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LISTING_NEW', 'New Listing Available'), ('LISTING_UPDATE', 'Listing Updated'), ('REQUEST_STATUS', 'Request Status Changed'), ('PICKUP_REMINDER', 'Pickup Reminder'), ('EXPIRY_WARNING', 'Expiry Warning'), ('VERIFICATION_UPDATE', 'Profile Verification Update'), ('DELIVERY_UPDATE', 'Delivery Status Update'), ('RATING_RECEIVED', 'New Rating Received')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
