# Generated by Django 5.1.6 on 2025-03-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_data_alter_notification_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LISTING_NEW', 'New Listing Available'), ('LISTING_UPDATE', 'Listing Updated'), ('REQUEST_STATUS', 'Request Status Changed'), ('PICKUP_REMINDER', 'Pickup Reminder'), ('EXPIRY_WARNING', 'Expiry Warning'), ('VERIFICATION_UPDATE', 'Profile Verification Update'), ('DELIVERY_UPDATE', 'Delivery Status Update'), ('RATING_RECEIVED', 'New Rating Received'), ('REPORT_GENERATED', 'Report Generated'), ('REPORT_ERROR', 'Report Generation Error'), ('SYSTEM', 'System Notification'), ('ERROR', 'Error Notification')], max_length=50),
        ),
    ]
