# Generated by Django 5.1.6 on 2025-03-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LISTING_NEW', 'New Listing Available'), ('LISTING_UPDATE', 'Listing Updated'), ('LISTING_INACTIVE', 'Listing Deactivated'), ('REQUEST_STATUS', 'Request Status Changed'), ('PICKUP_REMINDER', 'Pickup Reminder'), ('EXPIRY_WARNING', 'Expiry Warning'), ('VERIFICATION_UPDATE', 'Profile Verification Update'), ('DELIVERY_UPDATE', 'Delivery Status Update'), ('RATING_RECEIVED', 'New Rating Received')], max_length=50),
        ),
    ]
